-- Sprint 4 Week 19: Client Portal
-- Creates the portal_tokens table for shareable, read-only trip links.
-- Tokens are generated by the consultant and validated without Clerk auth.

CREATE TABLE portal_tokens (
  id         uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  trip_id    uuid NOT NULL REFERENCES trips(id) ON DELETE CASCADE,
  token      text NOT NULL UNIQUE,
  created_at timestamptz NOT NULL DEFAULT now(),
  expires_at timestamptz,
  revoked    boolean NOT NULL DEFAULT false
);

-- Fast lookup by token (used on every portal page load)
CREATE INDEX portal_tokens_token_idx ON portal_tokens(token);
-- Lookup by trip (used when listing/revoking tokens for a trip)
CREATE INDEX portal_tokens_trip_id_idx ON portal_tokens(trip_id);

ALTER TABLE portal_tokens ENABLE ROW LEVEL SECURITY;
-- Service-role key bypasses RLS; no policy needed for backend-only access.
